# ~/environment/sam-app/buildspec.yml

version: 0.2
env:
  variables:
    Version: "bank"
    Env: "dev"
    SecretManage: "arn:aws:secretsmanager:us-west-2:959525568826:secret:CredencialDBBankBotdev-mbHFbO"
    ClusterArn: "arn:aws:rds:us-west-2:959525568826:cluster:bankbotdev"
    # DBTableName: "chatbotqna"
    # BotName: "DigitalConnectQNA"
    # BotAlias: "digitalconnectqna"
    # s3Pipeline: "codepipeline-us-west-2-598446214898"
    # ecrLambda: 959525568826.dkr.ecr.us-west-2.amazonaws.com/snipstrainerqna
    # Email: zafir@digitalconnect.com.mx
    # PassEmail: desarrolloDC


phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      # Install packages or any pre-reqs in this phase.
      # Upgrading SAM CLI to latest version
      # - pip3 install --upgrade aws-sam-cli
      - sam --version
  
  #pre_build:
    #commands:
      # Run tests, lint scripts or any other pre-build checks.
      
  build:
    commands:
      # Use Build phase to build your artifacts (compile, etc.)
      - sam build

  post_build:
    commands:
      # Use Post-Build for notifications, git tags, upload artifacts to S3
      # - sam deploy --s3-bucket ${s3Pipeline}
      #   --stack-name BankBot-${Env}
      #   --region ${AWS_DEFAULT_REGION}
      #   --parameter-overrides Env=${Env} SecretManage=${SecretManage} ClusterArn=${ClusterArn} 
      #   DBTableName=${DBTableName} BotName=${BotName} BotAlias=${BotAlias} Email=${Email}
      #   PassEmail=${PassEmail} Version=$(Version)
      #   --capabilities CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND
      #   --kms-key-id ${CODEBUILD_KMS_KEY_ID}
      #   --image-repository ${ecrLambda}
      #   --no-confirm-changeset
      - sam deploy --s3-bucket ${s3Pipeline}
        --stack-name BankBot-${Env}
        --region ${AWS_DEFAULT_REGION}
        --parameter-overrides Env=${Env} Version=$(Version)
        --SecretManage=${SecretManage} ClusterArn=${ClusterArn} 
        --capabilities CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND
        --kms-key-id ${CODEBUILD_KMS_KEY_ID}
        --image-repository ${ecrLambda}
        --no-confirm-changeset

artifacts:
  discard-paths: yes
  #files:
    # List of local artifacts that will be passed down the pipeline
    #- packaged.yaml